project_id = "wzwqhfbmymrengjqikjl"

[functions.analyze-vinyl-swatch]
verify_jwt = false

[functions.generate-master]
verify_jwt = false

[functions.generate-3d]
verify_jwt = false

[functions.convert-print]
verify_jwt = false

[functions.approveflow-event]
verify_jwt = false

[functions.generate-color-render]
verify_jwt = false

[functions.send-klaviyo-event]
verify_jwt = false

[functions.sync-wc-approveflow]
verify_jwt = false

[functions.sync-wc-shopflow]
verify_jwt = false

[functions.sync-woo-manual]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.update-woo-order]
verify_jwt = false

[functions.track-affiliate-card-view]
verify_jwt = false

[functions.track-affiliate-signup]
verify_jwt = false

[functions.send-affiliate-access-link]
verify_jwt = true

[functions.affiliate-verify-login]
verify_jwt = false

[functions.affiliate-magic-link]
verify_jwt = false

[functions.generate-thumbnail]
verify_jwt = true

[functions.ups-track]
verify_jwt = false

[functions.realtime-quote-session]
verify_jwt = false

[functions.parse-voice-quote]
verify_jwt = false

[functions.send-mightychat-email]
verify_jwt = false

[functions.ai-detect-priority]
verify_jwt = false

[functions.receive-email-webhook]
verify_jwt = false

[functions.seed-contacts-from-woo]
verify_jwt = false
